name: Ruby Gem

on:
  push:
    branches: '**'

jobs:
  build:
    name: RSpec
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: ['2.7', '3.0', '3.1', head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: latest
    - run: bundle
    - run: bundle exec rspec
    - run: bundle exec gem build
